### ISSUE TITLE
Intermittent connection with RX (wrong baud rate?)

### ISSUE THREAD

**Issue by AFIDclan** [IronSavior/dsm2_tx#7]
Hey there. Loving your library!
I am having a slight issue where the connection between my tx and rx if very intermittent (roughly once a second)

I am wondering if the baud rate might be incorrect, or perhaps my 16mhz board won't work with this (arduino uno)

Any tips?

Thanks!

**Comment by AFIDclan** [comment]
YAY! FIXED!

You have to put a 22ms delay in the loop for it to run properly!

**Comment by IronSavior** [comment]
I love a happy ending. Depending on your tx circuit and receivers, you might be able to get away with 11ms as well. Also keep in mind that if your loop performs any expensive computations, you might have to tweak your timing mechanism to account for it. 

You can test the whole system by recording the output from your receiver channels with a logic analyzer. If you don't have one of those (kind of expensive for hobbyists), then you can use a second Arduino in place of the tx to read the serial output. That can help you measure the time interval between frames.

**Comment by AFIDclan** [comment]
I'll have to try 11ms. As of now, I'm trying to figure out the binding process. I accidentally unpaired my RC and TX and can't get them to bind back up...

**Comment by AFIDclan** [comment]
Changed the bind byte to 0x80 and got it to bind.
