### ISSUE TITLE
can I use it to generate a valid DSM2/X stream ?

### ISSUE THREAD

**Issue by AndKe** [IronSavior/dsm2_tx#8]
I have a Remote Reciever, and an autopilot that requires DSM/2/X stream (not sure which the remote receiver outputs) 
The goal is to control that autopilot by creating a valid ~112kbaud stream that will appear as if an remote receiver were connected.
Would you say your library can be used to help me do that, or anything else you know of ?
Thanks in advance.

**Comment by IronSavior** [comment]
The code here will send commands using the hardware UART (@ 115.2k baud) commonly found on Arduinos and all of the transmitter circuits I used were taken from MLP5DSM radios and one DX7 (which was pre-DSMX). I believe it could work with a DSMX transmitter circuit, but I don't recall if any of the MLP5DSM units I used were DSMX. This code sends data one-way: commands go to the transmitter and then to the receivers, but there is no return path.
