### ISSUE TITLE
error: use of undeclared identifier 'sleep'

### ISSUE THREAD

**Issue by TheNotary** [IronSavior/dsm2_tx#9]
It doesn't seem to work on mac, is there a dependency required?

**Comment by IronSavior** [comment]
Wouldn't have any idea. I never tried it on a mac and the project has 10+ years of dust on it.

**Comment by IronSavior** [comment]
My first instinct on this problem is that standard libraries may have changed since it was first written. You might try building against an older toolchain or toy with the command args to make the compiler use an older language standard.

**Comment by TheNotary** [comment]
oh my, I hand't looked closely enough at the date.  Well anyway thanks for uploading this, I switched it from sleep to delay (maybe they changed that in the more recent arduinos?) and it worked and appreciate you sharing this nifty mocking pattern (I got here from a thread you posted in years ago apparently about testing Arduino code) :D
